/**
 * `@clue-harness/kb` — the knowledge base engine (M2 skeleton).
 *
 * Business-package discipline (design §2.1): this package imports NO dsh
 * package — its only dsh-facing vocabulary (Branded, SessionId types) comes
 * through `@clue-harness/compat`, and path/IO helpers through
 * `@clue-harness/util`. The Cordis service face (ctx.kb) arrives in M3 when
 * the loop becomes its consumer — engines first, faces on demand.
 *
 * @module @clue-harness/kb
 */
export {
  DEFAULT_CHUNKER_VERSION,
  DEFAULT_KB_CONFIG,
  EMBED_NORM_VERSION,
  KB_FORMAT_VERSION,
  KbDocId,
  embedderVersion,
  // KbEntryId exports BOTH meanings: the brand type and its constructor.
  KbEntryId,
  REDLINE_PROPOSAL_RATIO,
  type ApprovalAction,
  type ApprovalRequest,
  type ChunkRecord,
  type DocAnchor,
  type DocRecord,
  type EntryDocRef,
  type KbConfig,
  type KbEntry,
  type KbHistoryEvent,
  type KbKind,
  type KbMeta,
  type KbProvenance,
  type KbRedline,
  type KbStatus,
  type KbTier,
  type SignalRecord,
  type SourceBinding,
} from './types.ts'
export {
  BM25_B,
  BM25_K1,
  bm25CountFields,
  bm25Fields,
  bm25fScore,
  bm25fScoreFrom,
  buildLexicalStats,
  displayScore,
  idf,
  rankableScore,
  type Bm25FieldWeights,
  type Bm25Fields,
  type Bm25Score,
  type Bm25CountFields,
  type LexicalStats,
  type PrecomputedFields,
  type StatsDoc,
  type TermFrequency,
} from './bm25.ts'
export { tokenize, tokenizeCounts } from './tokenize.ts'
export {
  buildLexicalIndex,
  DEFAULT_LEXICAL_BUDGET,
  entryProjectionHash,
  fingerprintLexicalEntries,
  fingerprintLexicalIndex,
  forgetLexicalIndex,
  lexicalCandidates,
  lexicalIndexDir,
  lexicalStatsFor,
  lexicalStatsFrom,
  loadLexicalIndex,
  mergeLexicalIndexes,
  LEXICAL_FIELD_ORDER,
  LEXICAL_INDEX_DIRNAME,
  LEXICAL_META_FILE,
  LEXICAL_POSTINGS_FILE,
  type FieldTriple,
  type LexicalCandidate,
  type LexicalEntryFacts,
  type LexicalIndex,
  type LexicalIndexBudget,
  type LexicalIndexLoad,
  type LexicalIndexMeta,
  type LexicalIndexReport,
  type LexicalIndexStatus,
  type LexicalPosting,
} from './lexical-index.ts'
export {
  chunkDocument,
  DEFAULT_CHUNKER,
  findHeadings,
  headingPathAt,
  needsRebuild,
  quoteAnchorOf,
  type ChunkerConfig,
  type ChunkDraft,
} from './chunker.ts'
export {
  chunksDir,
  detectDrift,
  docChunksPath,
  docExists,
  docIdFrom,
  docRecordPath,
  docSnapshotPath,
  docsDir,
  ingestSnapshot,
  latestDocIdFor,
  listDocIds,
  listDocs,
  normalizeSourcePath,
  readChunks,
  readDocRecord,
  readDocText,
  removeChunks,
  sha256FromString,
  writeChunks,
  type DocDrift,
  type IngestResult,
  type IngestSnapshotInput,
} from './docs.ts'
export {
  applyTransition,
  canTransition,
  clearNeedsReview,
  historyEvent,
  raiseNeedsReview,
  transitionTable,
  type TransitionTrigger,
} from './state-machine.ts'
export {
  appendSignal,
  buildSignal,
  discardThreshold,
  readSignals,
  windowScore,
  windowScores,
  type SignalInput,
} from './signals.ts'
export {
  KbStore,
  legacyWorkspaceClueDir,
  migrateWorkspaceKbsToCentral,
  openGlobalStore,
  openProjectStore,
  type AddEntryInput,
  type KbStoreOptions,
  type MigrationEntry,
  type MigrateOptions,
} from './store.ts'
export {
    WORKSPACES_REGISTRY_VERSION,
  addWorkspace,
  findWorkspace,
  getRenderSurface,
  listActiveWorkspaces,
  readWorkspaces,
  registerWorkspace,
  removeWorkspace,
  renameWorkspace,
  setRenderSurface,
  workspacesRegistryFile,
  isLiveRow,
  writeWorkspaces,
  type RenderSurfaceSettings,
  type WorkspaceRecord,
  type WorkspaceRegistry,
  type WorkspaceSource,
} from './workspaces.ts'
export {
  annotationsFor,
  DEFAULT_WEIGHTS,
  enrichHit,
  entryTextAfterRedlines,
  isRedlinedChar,
  queryKb,
  redlinedRatio,
  scoreEntry,
  type HitExplanation,
  type LexicalScorer,
  type QueryHit,
  type QueryOptions,
  type RetrievalWeights,
} from './query.ts'
export {
  DEFAULT_INJECT_MIN_ENTRY_CHARS,
  DEFAULT_INJECT_PER_ENTRY_CHARS,
  docAnnotation,
  renderHitLine,
} from './render.ts'
export {
  keepWorkspace,
  listTrash,
  panelWorkspaces,
  purgeAllOrphans,
  purgeWorkspace,
  sideTableFile,
  syncWorkspaces,
  trashDirFor,
  type HostWorkspaceRow,
  type PurgedPiece,
  WorkspaceNotPurgeableError,
  WorkspaceUnknownError,
  type WorkspaceSyncReport,
} from './workspace-sync.ts'
export {
  VECTOR_FORMAT_VERSION,
  cosineSimilarity,
  clearEmbedCache,
  countCachedVectors,
  decodeVectorMatrix,
  embedCacheDir,
  embedCacheFile,
  embedCacheKey,
  encodeVectorMatrix,
  l2Normalize,
  listVectorTargets,
  normalizeEmbedText,
  readCachedVector,
  readVectorIndex,
  removeVectorIndex,
  unitsFingerprint,
  vectorBinPath,
  vectorFileStem,
  vectorIndexStatuses,
  vectorMetaFor,
  vectorMetaPath,
  vectorsDir,
  writeCachedVector,
  writeVectorIndex,
  type VectorIndex,
  type VectorIndexMeta,
  type VectorIndexStatus,
  type VectorQuant,
  type VectorTarget,
} from './vectors.ts'
