/**
 * `clue kb` — the M2 manual surface of the knowledge base ("手动增删查,
 * 跑通流程"). Every command is thin: parse → open store(s) → call the
 * engine → print. All lifecycle logic lives in packages/kb.
 *
 *   clue kb add --kind pitfall --title "…" --text "…" [--tag t]… [--bind rel]… [--global]
 *   clue kb list [--status s] [--kind k] [--review] [--global]
 *   clue kb show <id> [--global]
 *   clue kb query <词…> [--include-expired] [--no-global] [--limit n] [--no-touch]
 *   clue kb approvals [--all]
 *   clue kb approve <requestId> | clue kb reject <requestId>
 *   clue kb reverify <id> [--accept]
 *   clue kb signal <id> <human-confirm|evidence-pass|implicit-use|evidence-fail|user-reject> [--note n]
 *   clue kb sweep          (过期/遗弃/清退 + 提升建议入队)
 *   clue kb workspace <list|add|rename|remove>   (M9: 工作区名单,ClueHarness 自己的)
 *   clue kb migrate        (把工作区里的 .clue/kb 收回到中心 ~/.clue,决策 #6 再修订)
 *   clue kb generalize [--dry-run] [--threshold n]  (跨项目泛化扫描)
 *   clue kb ingest <file> [--as rel] [--dry-run]    (M9-3: 原文入库,写入时切片)
 *   clue kb doc <list|attach|show>                  (M9-1: 原文快照与挂载)
 *   clue kb chunks <docId> [--query q] [--limit n]  (M9-2: 二级检索/浏览分片)
 *   clue kb detail <entryId> [--query q]            (M9-2: 按条目下钻原文段,纯读)
 *   clue kb redline <id> (--chars a-b | --lines a-b) --reason r   (M9-4: 人工划除)
 *   clue kb rebind <id> --bind <路径>… --reason r [--clear-review]  (改绑目标文件)
 *   clue kb split <id> --into <drafts.json>         (M9-4: 人工拆分 → superseded)
 *   clue kb status
 *
 * Exit codes: 0 ok · 2 usage/engine failure (no evidence semantics here —
 * kb is not a gate; the render CLI owns exit code 1).
 *
 * @module @clue-harness/cli/kb
 */
import path from 'node:path'
import { mkdir, readFile } from 'node:fs/promises'
import {
  KbEntryId,
  addWorkspace,
  entryTextAfterRedlines,
  migrateWorkspaceKbsToCentral,
  openGlobalStore,
  openProjectStore,
  queryKb,
  readWorkspaces,
  registerWorkspace,
  removeWorkspace,
  renameWorkspace,
  type DocAnchor,
  type KbKind,
  type KbStore,
  type SignalInput,
} from '@clue-harness/kb'
import { buildWorkLog, loadWorkLog, runEvidenceLoop, saveWorkLog, suggestGeneralizations } from '@clue-harness/kb-loop'
import { anchorLabel, ingestFile, queryChunks, renderDetailView, resolveChunkSources, type ChunkSource, type ChunkVectorState } from '@clue-harness/rag'
import { clueHome } from '@clue-harness/util'

const USAGE = `usage: clue kb <command> [options]

commands:
  add       --kind <fact|decision|snippet|map|pitfall|asset> --title <title> --text <text>
            [--tag <tag>]… [--bind <project-relative path>]… [--note <note>] [--global]
  list      [--status candidate|trusted|expired|discarded] [--kind k] [--review] [--global]
  show      <id> [--global]          full entry text + history + window score
  query     <terms…> [--include-expired] [--no-global] [--limit n] [--no-touch]
  approvals [--all]                  pending approval queue (the entry point for batch approvals)
  approve   <requestId>              approve (promote/discard/rescue/reactivate)
  reject    <requestId>              reject (no negative signal recorded: not approving ≠ the knowledge being wrong)
  promote   <id> [--reason <why>] [--global]
                                     human-only route: promote a candidate straight to trusted (no need to
                                     accumulate window score); leaves a history record + a human-confirm
                                     signal, and settles the entry's queued promote requests
  retire    <id> --reason <why> [--global]
                                     human-only route: a human ruling of "no longer holds" → expired (still
                                     readable, still reversible), clears the ⚑ flag; discarding remains a
                                     decision for evidence/approval
  reactivate <id> [--reason <why>] [--global]
                                     human-only route: expired → candidate (must earn trusted again)
  rescue    <id> [--reason <why>] [--global]
                                     human-only route: discarded → candidate (rescuing stops the 60-day
                                     purge countdown)
  reverify  <id> [--accept]          re-verify bindings; --accept accepts the new content and updates hashes
  signal    <id> <signal> [--note n] record a signal by hand (the five grades are listed above)
  worklog   --changed <f>… --referenced <id>… [--page p.html] [--out w.json]
                                     build the closed-loop worklog (auto-generated by the agent since M3b)
  loop      --worklog <w.json> [--mask <sel>]… [--no-inspect] [--no-sweep]
                                     run one evidence loop: classify → render verification (only when
                                     triggered) → attribution → record signals → maintenance
  sweep                              maintenance: expire / discard on strong negatives / 60-day purge /
                                     queue promotion suggestions
  migrate                            pull the legacy in-workspace layout (<project>/.clue/kb and
                                     render-baselines) into the central store <home>/kb/<workspace key>
                                     (never overwrites; report-based)
  generalize [--dry-run] [--threshold n]
                                     cross-project generalization scan: knowledge of the same kind
                                     verified in ≥2 projects → global candidate + pending promote
                                     (becomes global trusted once approved)
  ingest    <file.md|.html> [--as <project-relative path>] [--dry-run]
                                     document ingest: sha256, persisted as an immutable snapshot +
                                     chunking at write time (800/600)
                                     --dry-run only previews segments (heading/anchor/char count),
                                     writes no bytes at all
  doc       list [--global]          document snapshot inventory (docId/source/chars/mounted entries)
  doc       attach <id> --doc <docId> [--lines a-b] [--heading <path>] [--quote <opening text>]
                                     mount an evidence anchor onto an entry (the entry remains the
                                     governance subject)
  doc       show <docId> [--global]  snapshot metadata + chunk inventory (the full text is not printed)
  chunks    <docId> [--query q] [--limit n] [--max-chars n] [--global]
                                     chunk-level retrieval/browsing: per segment returns line numbers +
                                     heading + excerpt
  detail    <entryId> [--query q] [--limit n] [--global]
                                     drill down from an entry into document segments (read-only: records
                                     no signals, changes no state)
  redline   <id> (--chars a-b | --lines a-b) --reason <reason> [--global]
  rebind    <id> --bind <project-relative path>… --reason <why> [--clear-review] [--global]
                                     rebind an entry's bound files (previously settable only once, at
                                     creation): new paths must exist, the reason goes into history;
                                     --clear-review treats the rebind as a re-verification and clears
                                     the ⚑ along the way
                                     manual redline: the segment exits both display and scoring; a
                                     redlined share >40% automatically queues an approval proposal
  split     <id> --into <drafts.json> [--reason r] [--global]
                                     manual split: original entry → superseded (terminal), new entries
                                     start as candidate; evidence is inherited, governance is not
                                     (zero signals carry over)
  status                             overview: counts per status / needs review / pending approvals /
                                     store locations
  ltr                                offline LTR: reads ranklog + signal labels, reports readiness;
                                     with enough data fits offline and compares against the hand weights
                                     (report-only by default, changes no configuration)

vectors & reranking (V0–V2):
  embed-config show [--json]         embedding provider config (prints reference names and key status,
                                     never echoes key values)
  embed-config set [--base-url u] [--model m] [--api-key-env NAME] [--enable|--disable]
                   [--timeout-ms n] [--batch-size n] [--concurrency n] [--max-units n]
                   [--header k=v]…   write non-secret config (dim is not accepted by hand;
                                     test measures and writes it)
  embed-config key --stdin           write the key from stdin (key store/reference; never enters
                                     shell history, never echoed)
  embed-config unset-key             clear the key (the vector layer stays; only affects later calls)
  embed-config test [--no-record]    test the connection: echoes dim/latency/normalized magnitude
                                     and writes the measured dimension
  embed-config auto [--dry-run]      zero-config: probes which of the configured providers can really
                                     embed, enables the first success directly (with the measured
                                     dimension) — nothing else for you to fill in
  embed                              build/update the vector layer; --dry-run only tallies (zero calls,
                                     zero cost), --only entries|chunks|all, --rebuild forces a rebuild
  doctor [--json]                    vector-layer health (missing/expired/partial/dimension mismatch/
                                     unconfigured) + tuning items + ranklog
  query <terms…> --explain           hybrid retrieval + score decomposition (--channel/--rerank/--profile/--limit)
  query <terms…> --llm-rerank        runs one extra model rerank and prints its diff against the
                                     deterministic rerank (V5, off by default)

common: --project <dir> (defaults to the current directory; decides which workspace's store is
        used — zero residue inside the project directory)
        --home <dir> (central home root: every workspace store / the global store / the
        registry live here; defaults to $CLUE_HOME or ~/.clue)`

const KINDS: KbKind[] = ['fact', 'decision', 'snippet', 'map', 'pitfall', 'asset']
const SIGNALS: SignalInput[] = ['human-confirm', 'evidence-pass', 'implicit-use', 'evidence-fail', 'user-reject']

interface Args {
  command: string
  positional: string[]
  flags: Map<string, string[]>
}

function parse(argv: string[]): Args {
  const command = argv[0] ?? ''
  const positional: string[] = []
  const flags = new Map<string, string[]>()
  for (let i = 1; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg.startsWith('--')) {
      const name = arg.slice(2)
      const list = flags.get(name) ?? []
      const next = argv[i + 1]
      if (next !== undefined && !next.startsWith('--')) {
        list.push(next)
        i += 1
      } else {
        list.push('true')
      }
      flags.set(name, list)
    } else {
      positional.push(arg)
    }
  }
  return { command, positional, flags }
}

const flag = (args: Args, name: string): string | undefined => args.flags.get(name)?.[0]
const multi = (args: Args, name: string): string[] => args.flags.get(name)?.filter((v) => v !== 'true') ?? []
const has = (args: Args, name: string): boolean => args.flags.has(name)

async function stores(args: Args): Promise<{ project: KbStore; global: KbStore }> {
  const home = flag(args, 'home')
  const projectRoot = flag(args, 'project') ?? process.cwd()
  return {
    project: await openProjectStore(projectRoot, home),
    global: await openGlobalStore(home),
  }
}

function storeFor(args: Args, both: { project: KbStore; global: KbStore }): KbStore {
  return has(args, 'global') ? both.global : both.project
}

/**
 * Resolve the tier that OWNS one entry id (project first, then global) unless
 * --global pins it. Governance acts (attach/redline/split/detail) must reach
 * the entry's own store: the same id never lives in two tiers, and guessing
 * the wrong tier would silently no-op or create a second truth.
 * @param args - parsed CLI args.
 * @returns the owning store.
 */
async function entryStore(args: Args): Promise<{ store: KbStore; both: { project: KbStore; global: KbStore } }> {
  const both = await stores(args)
  if (has(args, 'global')) return { store: both.global, both }
  const id = args.positional[0]
  if (id === undefined) return { store: both.project, both }
  if (await both.project.get(KbEntryId(id)) !== null) return { store: both.project, both }
  if (await both.global.get(KbEntryId(id)) !== null) return { store: both.global, both }
  // Unknown id: fail in the addressed tier (the caller's next get() throws the
  // honest "条目不存在" instead of a confusing tier error).
  return { store: both.project, both }
}

/** Parse an `a-b` (or single `a`) inclusive range flag. */
function parseRange(value: string, label: string): [number, number] {
  const match = /^(\d+)(?:\s*-\s*(\d+))?$/.exec(value.trim())
  if (match === null) throw new Error(`${label} expects a-b or a single line/char number, got "${value}"`)
  const from = Number(match[1])
  const to = match[2] === undefined ? from : Number(match[2])
  if (from < 1 || to < from) throw new Error(`invalid ${label} range: ${value}`)
  return [from, to]
}

/** The quote anchor of one snapshot line (a human-readable anchor). */
async function quoteFromDoc(store: KbStore, docId: string, line: number): Promise<string> {
  const { readDocText } = await import('@clue-harness/kb')
  const text = await readDocText(store.dir, docId)
  if (text === null) return ''
  return (text.split('\n')[line - 1] ?? '').replace(/\s+/g, ' ').trim().slice(0, 40)
}

function entryLine(entry: { id: string; kind: string; title: string; status: string; needsReview: boolean; tier: string }): string {
  const review = entry.needsReview ? ' ⚑needs review' : ''
  return `${entry.id}  [${entry.status}${review}]  <${entry.kind}${entry.tier === 'global' ? ',global' : ''}>  ${entry.title}`
}

/** CLI entry; returns the process exit code. */
export async function kbMain(argv: string[]): Promise<number> {  const args = parse(argv)
  if (args.command === '' || has(args, 'help') || args.command === 'help') {
    console.log(USAGE)
    return 0
  }
  try {
    // Lazy anchors: the store pair is opened by the commands that actually
    // address a tier — `workspace`, `migrate` and `generalize` do not (they
    // work on the roster and the home), and eagerly opening it made them die
    // on an unwritable/absent launch anchor before doing any work at all.
    let cache: { project: KbStore; global: KbStore } | null = null
    const both = async (): Promise<{ project: KbStore; global: KbStore }> => cache ??= await stores(args)
    const store = async (): Promise<KbStore> => storeFor(args, await both())
    switch (args.command) {
      case 'add': {
        const kind = flag(args, 'kind') as KbKind | undefined
        const title = flag(args, 'title')
        const text = flag(args, 'text')
        if (kind === undefined || !KINDS.includes(kind)) throw new Error(`--kind must be one of ${KINDS.join('|')}`)
        if (title === undefined || text === undefined) throw new Error('add requires --title and --text')
        const entry = await (await store()).add({
          kind, title, text,
          tags: multi(args, 'tag'),
          bindings: multi(args, 'bind'),
          note: flag(args, 'note'),
        })
        console.log(`added (candidate): ${entryLine(entry)}`)
        if (entry.bindings.length > 0) console.log(`  bindings: ${entry.bindings.map((b) => `${b.path}@${b.contentHash.slice(0, 8)}`).join(', ')}`)
        return 0
      }
      case 'list': {
        const status = flag(args, 'status')
        const kind = flag(args, 'kind')
        const entries = await (await store()).list({
          ...(status !== undefined ? { status: status as never } : {}),
          ...(kind !== undefined ? { kind: kind as never } : {}),
          ...(has(args, 'review') ? { needsReview: true } : {}),
        })
        for (const entry of entries) console.log(entryLine(entry))
        const addressed = await store()
        console.log(`${entries.length} entries in total (${addressed.tier === 'global' ? 'global tier' : `project tier ${addressed.dir}`})`)
        return 0
      }
      case 'show': {
        const id = args.positional[0]
        if (id === undefined) throw new Error('show requires an entry id')
        const entry = await (await store()).get(KbEntryId(id))
        if (entry === null) throw new Error(`entry not found: ${id}`)
        const score = await (await store()).score(entry.id)
        console.log(JSON.stringify({ ...entry, windowScore: score }, null, 2))
        return 0
      }
      case 'query': {
        const text = args.positional.join(' ')
        if (text.trim() === '') throw new Error('query requires search terms')
        // V2: `--explain` shows the score decomposition, which only the hybrid
        // plane can produce — so this flag routes through the SAME retriever
        // the model's kb_search uses, with the same settings.
        if (has(args, 'explain') || has(args, 'channel') || has(args, 'rerank') || has(args, 'profile') || has(args, 'llm-rerank')) {
          const { openEmbeddingHost } = await import('@clue-harness/kb-face/embedding-host')
          const cli = await import('./embed-cli.ts')
          const host = await openEmbeddingHost()
          try {
            const anchors = await both()
            return await cli.queryExplainRun(host, { ...anchors, home: flag(args, 'home') ?? clueHome(), args })
          } finally {
            await host.close()
          }
        }
        const anchors = await both()
        const hits = await queryKb(
          anchors.project,
          has(args, 'no-global') ? null : anchors.global,
          {
            text,
            includeExpired: has(args, 'include-expired'),
            limit: flag(args, 'limit') !== undefined ? Number(flag(args, 'limit')) : undefined,
            noTouch: has(args, 'no-touch'),
            // The console is English; the same annotations feed the model blocks
            // and the web panel (Chinese), so the surface chooses.
            annotationLanguage: 'en',
          },
        )
        if (hits.length === 0) { console.log('no hits'); return 0 }
        for (const hit of hits) {
          console.log(`▸ [${hit.score}] ${entryLine(hit.entry)}`)
          console.log(`  matched: ${hit.matched.join(', ')}`)
          // M9-4: what a reader sees here is what the model sees — redlined
          // segments are gone from BOTH. The raw text stays available through
          // `clue kb show` for the human doing the governance.
          const body = entryTextAfterRedlines(hit.entry).replace(/\s+/g, ' ').trim()
          if (body !== '') console.log(`  text: ${body.length > 300 ? `${body.slice(0, 300)}…` : body}`)
          if (hit.entry.doc !== undefined) console.log(`  document: ${hit.entry.doc.docId} (drill down: clue kb detail ${hit.entry.id} --query <terms>)`)
          for (const note of hit.annotations) console.log(`  ⚠ ${note}`)
        }
        return 0
      }
      case 'approvals': {
        const seen = new Set<string>()
        const anchors = await both()
        for (const tier of [anchors.project, anchors.global]) {
          const requests = await tier.listApprovals(!has(args, 'all'))
          for (const request of requests) {
            seen.add(request.id)
            const entry = await tier.get(request.entryId)
            console.log(`${request.id}  [${request.action}]  score ${request.scoreAtRequest}  ${request.reason}`)
            if (entry !== null) console.log(`  → ${entryLine(entry)}`)
          }
        }
        if (seen.size === 0) console.log(has(args, 'all') ? 'the queue is empty' : 'no pending approval requests (sweep generates promotion suggestions by score)')
        return 0
      }
      case 'approve':
      case 'reject': {
        const requestId = args.positional[0]
        if (requestId === undefined) throw new Error(`${args.command} requires a request id`)
        const anchors = await both()
        for (const tier of [anchors.project, anchors.global]) {
          const pending = await tier.listApprovals(true)
          if (!pending.some((a) => a.id === requestId)) continue
          const { request, entry } = await tier.resolveApproval(requestId, args.command === 'approve')
          console.log(`${args.command === 'approve' ? 'approved' : 'rejected'} [${request.action}] ${request.entryId}`)
          if (entry !== null) console.log(`  → ${entryLine(entry)}`)
          return 0
        }
        throw new Error(`pending approval request not found: ${requestId}`)
      }
      case 'promote': {
        const id = args.positional[0]
        if (id === undefined) throw new Error('promote requires an entry id')
        // Governance act → the entry's OWN tier (entryStore), never a guess.
        const { store: addressed } = await entryStore(args)
        const reason = flag(args, 'reason')
        const { entry, requests } = await addressed.promote(KbEntryId(id), {
          by: 'cli',
          ...(reason !== undefined ? { reason } : {}),
        })
        console.log(`promoted to trusted: ${entryLine(entry)}`)
        console.log(`  reason: ${entry.history[entry.history.length - 1]?.reason ?? '(not recorded)'}`)
        if (requests.length > 0) {
          console.log(`  also settled ${requests.length} queued promote requests: ${requests.map((r) => r.id).join(', ')}`)
        }
        return 0
      }
      case 'retire':
      case 'reactivate':
      case 'rescue': {
        const id = args.positional[0]
        if (id === undefined) throw new Error(`${args.command} requires an entry id`)
        const { store: addressed } = await entryStore(args)
        const reason = flag(args, 'reason')
        const input = { by: 'cli', ...(reason !== undefined ? { reason } : {}) }
        const { entry, requests } = args.command === 'retire'
          ? await addressed.retire(KbEntryId(id), input)
          : args.command === 'reactivate'
            ? await addressed.reactivate(KbEntryId(id), input)
            : await addressed.rescue(KbEntryId(id), input)
        const verb = args.command === 'retire' ? 'ruled no longer holds (moved to expired)' : args.command === 'reactivate' ? 'reactivated (back to candidate)' : 'rescued back to candidate'
        console.log(`${verb}: ${entryLine(entry)}`)
        console.log(`  reason: ${entry.history[entry.history.length - 1]?.reason ?? '(not recorded)'}`)
        if (requests.length > 0) {
          console.log(`  also settled ${requests.length} queued requests: ${requests.map((r) => r.id).join(', ')}`)
        }
        return 0
      }
      case 'reverify': {
        const id = args.positional[0]
        if (id === undefined) throw new Error('reverify requires an entry id')
        const entry = await (await store()).reverify(KbEntryId(id), has(args, 'accept'))
        console.log(`reverified: ${entryLine(entry)}${entry.needsReview ? ` (still needs review: ${entry.reviewReason})` : ''}`)
        return 0
      }
      case 'rebind': {
        // 落地计划 §9: 绑定的**目标**此前没有任何办法改 —— `add` 只在创建时设一次,
        // `reverify --accept` 只重算已有路径的哈希(文件没了还会直接拒绝)。于是"知识
        // 锚在一份已被合并/删除的文档上"就卡死了,只能再加一条重复条目 —— 而重复条目
        // 正是绑定机制要防的"双真相"。这条命令就是那个缺失的出口:人是唯一的执行者,
        // 理由进履历,新路径必须真实存在。
        const id = args.positional[0]
        const reason = flag(args, 'reason')
        if (id === undefined || reason === undefined) {
          throw new Error('rebind requires <id> --reason <why>, plus --bind <project-relative path> (repeatable; omit to clear all bindings)')
        }
        const paths = multi(args, 'bind')
        const addressed = await store()
        const entry = await addressed.setBindings(KbEntryId(id), paths, reason, { clearReview: has(args, 'clear-review') })
        console.log(`rebound: ${entryLine(entry)}`)
        console.log(`  ${entry.bindings.length} bindings: ${entry.bindings.map((binding) => `${binding.path}@${binding.contentHash.slice(0, 8)}`).join(', ') || '(none)'}`)
        console.log(`  history recorded the rebind (reason: ${reason})${entry.needsReview ? ` · still needs review: ${entry.reviewReason}` : ''}`)
        return 0
      }
      case 'signal': {
        const id = args.positional[0]
        const signal = args.positional[1] as SignalInput | undefined
        if (id === undefined || signal === undefined || !SIGNALS.includes(signal)) {
          throw new Error(`signal requires <id> <${SIGNALS.join('|')}>`)
        }
        const addressed = await store()
        const record = await addressed.recordSignal(KbEntryId(id), signal, flag(args, 'note') ?? '')
        const score = await addressed.score(KbEntryId(id))
        console.log(`signal recorded ${record.polarity}/${record.source} weight ${record.weight}; window score now ${score.score} (threshold ±${addressed.config.trustThreshold})`)
        return 0
      }
      case 'worklog': {
        const changed = multi(args, 'changed')
        const referenced = multi(args, 'referenced')
        if (changed.length === 0) throw new Error('worklog requires --changed <file> (repeatable)')
        const log = buildWorkLog({
          projectRoot: flag(args, 'project') ?? process.cwd(),
          changedFiles: changed,
          referencedEntryIds: referenced,
          ...(flag(args, 'page') !== undefined ? { page: flag(args, 'page') } : {}),
          ...(flag(args, 'note') !== undefined ? { note: flag(args, 'note') } : {}),
        })
        const out = flag(args, 'out')
          ?? path.join(flag(args, 'home') ?? clueHome(), 'worklogs', `worklog-${Date.now().toString(36)}.json`)
        if (flag(args, 'out') === undefined) await mkdir(path.dirname(out), { recursive: true })
        await saveWorkLog(out, log)
        console.log(`worklog written: ${out}`)
        console.log(`  ${log.changedFiles.length} files changed · ${log.referencedEntryIds.length} entries referenced${log.page !== undefined ? ` · page ${log.page}` : ''}`)
        console.log('  next: clue kb loop --worklog ' + out)
        return 0
      }
      case 'loop': {
        const file = flag(args, 'worklog')
        if (file === undefined) throw new Error('loop requires --worklog <file>')
        const log = await loadWorkLog(file)
        const report = await runEvidenceLoop({
          worklog: has(args, 'no-inspect') ? { ...log, page: undefined } : log,
          home: flag(args, 'home'),
          maskSelectors: multi(args, 'mask'),
          noSweep: has(args, 'no-sweep'),
        })
        console.log(`classify: ${report.renderable.length} renderable${report.renderable.length > 0 ? ` (${report.renderable.join(', ')})` : ''} · ${report.other.length} other`)
        if (report.renderable.length === 0) {
          console.log('trigger rule: this change touches no renderable files → no render verification (backend-only rounds never open a browser)')
        } else if (report.outcome === null) {
          console.log('no render verification (the worklog has no --page, or --no-inspect)')
        } else {
          const outcome = report.outcome
          console.log(`verify: ${outcome.exitOk ? '✓ passed' : `✗ ${outcome.errorCount} error-level evidence items`}`)
          for (const failure of outcome.failedAssertions.slice(0, 5)) console.log(`  ✗ ${failure}`)
          for (const entry of outcome.errorEntrySummaries.slice(0, 5)) console.log(`  ✗ ${entry}`)
        }
        for (const signal of report.recorded) {
          console.log(`signal: ${signal.entryId} ← ${signal.note}`)
        }
        for (const item of report.plan?.unattributed ?? []) {
          console.log(`no signal recorded: ${item.entryId} — ${item.reason}`)
        }
        for (const id of report.needsReviewRaised) console.log(`⚑ auto-flagged needs review: ${id}`)
        if (report.sweep !== null) {
          const swept = report.sweep
          console.log(`maintenance: ${swept.expired.length} expired · ${swept.discarded.length} discarded on strong negatives · ${swept.purged.length} purged · ${swept.promotions.length} new promotion suggestions`)
          for (const request of swept.promotions) console.log(`  ⇧pending promote ${request.entryId} (${request.reason})`)
        }
        return 0
      }
      case 'sweep': {
        const anchors = await both()
        const result = { project: await anchors.project.sweep(), global: await anchors.global.sweep() }
        for (const [tierName, swept] of Object.entries(result)) {
          console.log(`[${tierName}] ${swept.expired.length} expired · ${swept.discarded.length} discarded on strong negatives · ${swept.purged.length} purged · ${swept.promotions.length} new promotion suggestions`)
          for (const id of swept.expired) console.log(`  ↓expired ${id}`)
          for (const id of swept.discarded) console.log(`  ↓discarded ${id}`)
          for (const id of swept.purged) console.log(`  ✗purged (past the retention period) ${id}`)
          for (const request of swept.promotions) console.log(`  ⇧pending promote ${request.entryId} (${request.reason})`)
        }
        console.log('note: run clue kb approvals to see the pending queue, approve/reject to process it')
        return 0
      }
      case 'generalize': {
        // M5: cross-project scan — same knowledge verified in ≥2 projects
        // becomes a global candidate + a promote approval (决策 #14 泛化提议).
        const threshold = flag(args, 'threshold')
        const scan = await suggestGeneralizations({
          home: flag(args, 'home'),
          ...(threshold !== undefined ? { threshold: Number(threshold) } : {}),
          ...(has(args, 'dry-run') ? { dryRun: true } : {}),
        })
        console.log(`scanned ${scan.projectsScanned} project stores (similarity threshold ${threshold ?? 0.5})`)
        for (const proposal of scan.proposals) {
          const sources = proposal.sources.map((s) => `${s.entryId}@${path.basename(s.projectRoot)}`).join(' + ')
          if (proposal.created !== undefined) {
            console.log(`⇧generalization proposal "${proposal.draft.title}" ← ${sources}`)
            console.log(`  global candidate ${proposal.created.entry.id} queued for approval (${proposal.created.request.id})`)
          } else {
            console.log(`⇧[dry-run] generalization proposal "${proposal.draft.title}" ← ${sources}`)
          }
        }
        for (const reason of scan.skipped) console.log(`· skipped: ${reason}`)
        if (scan.proposals.length === 0) console.log('no new generalization proposals (knowledge of the same kind must be verified in ≥2 separate projects)')
        else console.log('note: run clue kb approvals to see the pending queue (both tiers are listed); once approved it becomes global trusted knowledge')
        return 0
      }
      case 'workspace': {
        // M9: the roster is ClueHarness's OWN workspace list (settings panel
        // and generalize scan both read it) — dsh's workspace service is never
        // consulted; a path is the only input taken from outside.
        const home = flag(args, 'home')
        const verb = args.positional[0] ?? 'list'
        if (verb === 'list') {
          const records = await readWorkspaces(home)
          for (const record of records) {
            console.log(`${record.key}  [${record.label}]  ${record.root}  (${record.source}, last seen ${record.lastSeenAt})`)
            if (record.renderSurface !== undefined) console.log(`  render surface override: ${JSON.stringify(record.renderSurface)}`)
          }
          console.log(`${records.length} workspaces in total (central home ${path.join(home ?? clueHome(), 'kb')})`)
          return 0
        }
        if (verb === 'add') {
          const target = args.positional[1]
          if (target === undefined) throw new Error('workspace add requires <dir>')
          const record = await addWorkspace(target, args.positional[2], home)
          const store = await openProjectStore(record.root, home)
          console.log(`registered: ${record.key} [${record.label}] ${record.root}`)
          console.log(`  central store: ${store.dir}`)
          return 0
        }
        if (verb === 'rename') {
          const key = args.positional[1]
          const label = args.positional.slice(2).join(' ')
          if (key === undefined || label === '') throw new Error('workspace rename requires <key> <label>')
          const record = await renameWorkspace(key, label, home)
          console.log(`renamed: ${record.key} → [${record.label}]`)
          return 0
        }
        if (verb === 'remove') {
          const key = args.positional[1]
          if (key === undefined) throw new Error('workspace remove requires <key>')
          const { record, kbDir, baselinesDir } = await removeWorkspace(key, home)
          console.log(`unregistered: ${record.key} [${record.label}] ${record.root}`)
          console.log(`  data not deleted: ${kbDir} · ${baselinesDir} (using that directory again re-registers it automatically)`)
          return 0
        }
        throw new Error(`unknown workspace subcommand: ${verb} (list|add|rename|remove)`)
      }
      case 'migrate': {
        // M9 (decision #6 re-revision): pull the M8 workspace-bound state back
        // into the central home. Never overwrites; leftovers are reported.
        const report = await migrateWorkspaceKbsToCentral({
          home: flag(args, 'home'),
          roots: multi(args, 'root'),
          ...(has(args, 'dry-run') ? { dryRun: true } : {}),
        })
        for (const item of report) {
          console.log(`${item.moved ? '✔ pulled in' : '· kept'} [${item.kind}] ${item.from}${item.to ? ` → ${item.to}` : ''} — ${item.reason}`)
        }
        const moved = report.filter((r) => r.moved).length
        if (report.length === 0) console.log('no workspace state to pull in (the central layout is already in place, or the workspace has no .clue)')
        else console.log(`${moved} items pulled into the central home, ${report.length - moved} kept as-is`)
        // Roots named by the legacy registry get re-registered even when their
        // .clue is already gone, so `workspace list` reflects the truth.
        for (const root of multi(args, 'root')) await registerWorkspace(root, { home: flag(args, 'home'), source: 'manual' })
        return 0
      }
      case 'ingest': {
        // M9-3: the ONE moment knowledge text is sliced. The report is the
        // user's evidence — every段's heading path, anchor and size, printed
        // before anything is mounted (mounting is `kb doc attach`, a human act).
        const file = args.positional[0]
        if (file === undefined) throw new Error('ingest requires <file.md|.html>')
        const addressed = await store()
        const report = await ingestFile({
          store: addressed,
          file: path.resolve(flag(args, 'project') ?? process.cwd(), file),
          ...(flag(args, 'as') !== undefined ? { sourcePath: flag(args, 'as') as string } : {}),
          ...(has(args, 'dry-run') ? { dryRun: true } : {}),
        })
        console.log(`${report.dryRun ? '[dry-run] ' : ''}document: ${report.sourcePath} (${report.format}, ${report.bytes} bytes → ${report.chars} chars, ${report.lineCount} lines)`)
        console.log(`chunking: ${report.chunks.length} segments · chunker ${report.chunkerVersion}`)
        for (const note of report.notes) console.log(`  · ${note}`)
        for (const chunk of report.chunks) {
          const overlap = chunk.overlapWith === undefined ? '' : ` · overlaps segment ${chunk.overlapWith}`
          console.log(`  segment ${chunk.seq} lines ${chunk.lines.start}-${chunk.lines.end} · ${chunk.chars} chars · ${chunk.headingPath === '' ? '(no heading)' : chunk.headingPath}${overlap}`)
          console.log(`      anchor: "${chunk.quoteAnchor}"`)
        }
        if (report.dryRun) {
          console.log('dry-run: no bytes written; drop --dry-run to persist it as an immutable snapshot')
        } else if (report.doc !== undefined) {
          console.log(`snapshot: ${report.doc.docId}${report.reused ? ' (identical bytes reused, no duplicate created)' : ''}${report.doc.supersedes !== undefined ? ` · supersedes ${report.doc.supersedes}` : ''}`)
          console.log(`next: clue kb doc attach <entry id> --doc ${report.doc.docId} --lines <a-b> (evidence mounting; entry generation is not automatic)`)
        }
        return 0
      }
      case 'doc': {
        const verb = args.positional[0] ?? 'list'
        if (verb === 'list') {
          const addressed = await store()
          const docs = await addressed.listDocs()
          const entries = await addressed.list()
          for (const doc of docs) {
            const mounted = entries.filter((entry) => entry.doc !== undefined && String(entry.doc.docId) === String(doc.docId))
            console.log(`${doc.docId}  ${doc.sourcePath}  ${doc.sizeChars} chars/${doc.lineCount} lines  ${doc.ingestedAt}${doc.supersedes !== undefined ? `  supersedes ${doc.supersedes}` : ''}`)
            console.log(`  mounted entries ${mounted.length}${mounted.length > 0 ? `: ${mounted.map((entry) => entry.id).join(', ')}` : ' (none — the document exists but is not mounted onto any knowledge yet)'}`)
          }
          if (docs.length === 0) console.log('no document snapshots; import one with clue kb ingest <file>')
          return 0
        }
        if (verb === 'show') {
          const docId = args.positional[1]
          if (docId === undefined) throw new Error('doc show requires <docId>')
          const addressed = await store()
          const record = await addressed.getDoc(docId)
          if (record === null) throw new Error(`document not found: ${docId}`)
          const chunks = await addressed.getChunks(docId)
          console.log(JSON.stringify(record, null, 2))
          console.log(`${chunks.length} chunks${await addressed.chunksNeedRebuild(docId) ? ' (version mismatch, will rebuild on the next query)' : ''}:`)
          for (const chunk of chunks) {
            console.log(`  segment ${chunk.seq} lines ${chunk.startLine}-${chunk.endLine} · ${chunk.chars} chars · ${chunk.headingPath === '' ? '(no heading)' : chunk.headingPath}`)
          }
          return 0
        }
        if (verb === 'attach') {
          const id = args.positional[1]
          const docId = flag(args, 'doc')
          if (id === undefined || docId === undefined) throw new Error('doc attach requires <entry id> --doc <docId>')
          const addressed = await entryStore(args)
          const lines = flag(args, 'lines')
          let anchor: DocAnchor | undefined
          if (lines !== undefined) {
            const range = parseRange(lines, '--lines')
            const quote = flag(args, 'quote') ?? await quoteFromDoc(addressed.store, docId, range[0])
            anchor = {
              lines: range,
              quoteAnchor: quote,
              ...(flag(args, 'heading') !== undefined ? { headingPath: flag(args, 'heading') as string } : {}),
            }
          }
          const entry = await addressed.store.attachDoc(KbEntryId(id), docId, anchor)
          console.log(`evidence mounted: ${entryLine(entry)}`)
          if (entry.doc?.anchor !== undefined) console.log(`  anchor: ${entry.doc.anchor.lines?.join('-') ?? ''} · "${entry.doc.anchor.quoteAnchor}"`)
          console.log('  note: the entry remains the sole governance subject; changes to the source document only flag this entry for review, they never rewrite the snapshot')
          return 0
        }
        throw new Error(`unknown doc subcommand: ${verb} (list|show|attach)`)
      }
      case 'chunks': {
        const docId = args.positional[0]
        if (docId === undefined) throw new Error('chunks requires <docId> (or --entry <id>)')
        const addressed = await store()
        // V4: when an embedder is configured, the second level fuses the lexical
        // and vector channels; otherwise this is exactly the old lexical path.
        const { openEmbeddingHost } = await import('@clue-harness/kb-face/embedding-host')
        const { planeChunkVector } = await import('./embed-cli.ts')
        const embedHost = await openEmbeddingHost()
        let vector = null
        try {
          vector = planeChunkVector(embedHost, flag(args, 'home') ?? clueHome())
        } finally {
          if (vector === null) await embedHost.close()
        }
        // A holder rather than a `let`: the state is assigned inside a callback,
        // which TypeScript's control-flow analysis does not follow (a plain
        // variable narrows to `never`).
        const stateRef: { current: ChunkVectorState | null } = { current: null }
        const source: ChunkSource = { store: addressed, docId }
        const hits = await queryChunks(source, {
          ...(vector !== null ? { vector: { ...vector, onState: (v: ChunkVectorState) => { stateRef.current = v } } } : {}),
          query: args.positional.slice(1).join(' ') || (flag(args, 'query') ?? ''),
          limit: flag(args, 'limit') !== undefined ? Number(flag(args, 'limit')) : undefined,
          maxChars: flag(args, 'max-chars') !== undefined ? Number(flag(args, 'max-chars')) : undefined,
        })
        if (vector !== null) await embedHost.close()
        if (stateRef.current !== null && stateRef.current.status !== 'used') console.log(`  ⚠ ${stateRef.current.note}`)
        if (hits.length === 0) { console.log('no hits'); return 0 }
        for (const hit of hits) {
          // A browsing pass (no query) has no relevance to report — printing a
          // 0 would read as "irrelevant" instead of "no query was given".
          const score = hit.score > 0 ? ` [${hit.score}]` : ''
          console.log(`▸${score} ${anchorLabel(hit, 'en')}${hit.partialRedline ? ' ⚠partially redlined' : ''}`)
          for (const line of hit.excerpt.split('\n')) console.log(`    | ${line}`)
        }
        return 0
      }
      case 'detail': {
        const id = args.positional[0]
        if (id === undefined) throw new Error('detail requires <entry id>')
        const addressed = await entryStore(args)
        const entry = await addressed.store.get(KbEntryId(id))
        if (entry === null) throw new Error(`entry not found: ${id}`)
        const sources = await resolveChunkSources(addressed.store, { entryId: id })
        const hits: Awaited<ReturnType<typeof queryChunks>> = []
        for (const source of sources) {
          hits.push(...await queryChunks(source, {
            query: flag(args, 'query') ?? '',
            limit: flag(args, 'limit') !== undefined ? Number(flag(args, 'limit')) : undefined,
          }))
        }
        const view = renderDetailView({
          entryId: entry.id,
          title: entry.title,
          docIds: sources.map((source) => source.docId),
          hits,
          noDoc: entry.doc === undefined,
        }, undefined, 'en')
        console.log(view.text)
        return 0
      }
      case 'redline': {
        // M9-4 5a: 人工划除。No model path reaches this — the CLI is one of the
        // two human surfaces (web panel is the other).
        const id = args.positional[0]
        const reason = flag(args, 'reason')
        if (id === undefined || reason === undefined) {
          throw new Error('redline requires <id> --reason <reason>, plus one of --chars a-b (entry text) or --lines a-b (document lines)')
        }
        const chars = flag(args, 'chars')
        const lines = flag(args, 'lines')
        if ((chars === undefined) === (lines === undefined)) {
          throw new Error('redline requires exactly one of --chars a-b and --lines a-b')
        }
        const addressed = await entryStore(args)
        const result = chars !== undefined
          ? await addressed.store.redlineText(KbEntryId(id), { chars: parseRange(chars, '--chars'), reason, by: 'cli' })
          : await addressed.store.redlineDocLines(KbEntryId(id), {
            lines: parseRange(lines as string, '--lines'),
            reason,
            by: 'cli',
            ...(flag(args, 'heading') !== undefined ? { headingPath: flag(args, 'heading') as string } : {}),
          })
        const { entry, ratio, proposal } = result
        console.log(`redlined (${chars !== undefined ? 'entry text' : 'document lines'}): ${entryLine(entry)}`)
        console.log(`  redlined share ${(ratio * 100).toFixed(1)}% · scoring and display both take effect now; for document-layer details use kb detail ${entry.id}`)
        if (proposal !== null) console.log(`  ⇧approval proposal queued ${proposal.id}: ${proposal.reason} (proposed by the system, executed by a human: clue kb split or discard)`)
        return 0
      }
      case 'split': {
        // M9-4 5b: 人工拆分。Inheritance boundary: evidence yes, governance no.
        const id = args.positional[0]
        const into = flag(args, 'into')
        if (id === undefined || into === undefined) throw new Error('split requires <id> --into <drafts.json>')
        const raw = JSON.parse(await readFile(into, 'utf8')) as unknown
        const list = Array.isArray(raw) ? raw : (raw as { drafts?: unknown }).drafts
        if (!Array.isArray(list) || list.length === 0) throw new Error('the drafts file must be an array, or { drafts: [...] } (at least one item)')
        const drafts = list.map((item, index) => {
          const draft = item as { kind?: KbKind; title?: unknown; text?: unknown; tags?: unknown; anchor?: DocAnchor }
          if (typeof draft.title !== 'string' || typeof draft.text !== 'string') {
            throw new Error(`draft[${index}] requires title and text (string)`)
          }
          return {
            ...(draft.kind !== undefined ? { kind: draft.kind } : {}),
            title: draft.title,
            text: draft.text,
            ...(Array.isArray(draft.tags) ? { tags: draft.tags.map(String) } : {}),
            ...(draft.anchor !== undefined ? { anchor: draft.anchor } : {}),
          }
        })
        const addressed = await entryStore(args)
        const reason = flag(args, 'reason') ?? '人工拆分'
        const { old, created } = await addressed.store.splitEntry(KbEntryId(id), drafts, reason)
        console.log(`split done: ${entryLine(old)} → superseded (terminal, never purged)`)
        for (const child of created) {
          console.log(`  new entry: ${entryLine(child)}${child.doc !== undefined ? ` · evidence carried over from ${child.doc.docId}` : ''}`)
        }
        console.log('  governance is not inherited: new entries start as candidate; signals/approvals/redlines all start from zero (anti-laundering)')
        return 0
      }
      case 'ltr': {
        // V5 (原规划 §8.4): the OFFLINE half of learning-to-rank. It reads the
        // ranklog the retrievals have been writing, joins it against the signal
        // ledger for labels, reports readiness, and — only when the data is
        // enough — fits a logistic model and compares it with the shipped hand
        // weights. Nothing here runs at retrieval time.
        const addressed = await store()
        const rag = await import('@clue-harness/rag')
        const { readSignals } = await import('@clue-harness/kb')
        const rows = await rag.readRankLog(addressed.dir)
        const signals = await readSignals(path.join(addressed.dir, 'signals.jsonl'))
        const training = rag.buildTrainingSet(rows, signals)
        const readiness = rag.ltrReadiness(training)
        console.log(`ranklog ${rows.length} rows · ${training.length} labeled samples (${readiness.positives} positive / ${readiness.negatives} negative) · ${readiness.queries} labeled queries`)
        console.log(`ready: ${readiness.ready ? 'yes' : 'no'} — ${readiness.reason}`)
        if (!readiness.ready) {
          console.log('note: labels come from the signal ledger (kb_cite/human-confirm/evidence-pass are positive, user-reject/evidence-fail are negative);')
          console.log('      only signals recorded within 7 days after a retrieval count as its label; keep using and citing knowledge to accumulate data')
          return 0
        }
        const model = rag.trainLogistic(training)
        const hand = rag.evaluateWeights(training, rag.handWeights())
        const learned = rag.evaluateWeights(training, model.weights)
        console.log('')
        console.log(`offline fit (${model.epochs} epochs, loss ${model.loss.toFixed(4)}) vs the shipped hand weights — comparison on the same labeled set:`)
        console.log(`  hand weights   : P@1 ${(hand.precisionAt1 * 100).toFixed(1)}% · MRR ${hand.mrr.toFixed(3)} (${hand.queries} queries)`)
        console.log(`  learned weights: P@1 ${(learned.precisionAt1 * 100).toFixed(1)}% · MRR ${learned.mrr.toFixed(3)} (${learned.queries} queries)`)
        console.log('  (a comparison on the same data is only lower-bound evidence; going live first requires a query-grouped holdout set)')
        console.log(`  learned weights: ${Object.entries(model.weights).map(([k, v]) => `${k}=${v.toFixed(3)}`).join(' ')}`)
        console.log('note: this command only reports; it never rewrites the feature weights in settings (original plan §8.4: offline experiments first, then a human decides)')
        return 0
      }
      case 'status': {
        const roster = await readWorkspaces(flag(args, 'home'))
        if (roster.length > 0) {
          console.log(`[workspace roster] ${roster.length} workspaces`)
          for (const record of roster) console.log(`  ${record.key}  [${record.label}]  ${record.root}`)
        }
        const anchors = await both()
        for (const tier of [anchors.project, anchors.global]) {
          const entries = await tier.list()
          const byStatus = entries.reduce<Record<string, number>>((acc, e) => { acc[e.status] = (acc[e.status] ?? 0) + 1; return acc }, {})
          const review = entries.filter((e) => e.needsReview).length
          const pending = (await tier.listApprovals(true)).length
          console.log(`[${tier.tier === 'global' ? 'global tier' : 'project tier'}] ${tier.dir}`)
          console.log(`  ${entries.length} entries: ${Object.entries(byStatus).map(([k, v]) => `${k}=${v}`).join(' ') || '(empty)'} · needs review ${review} · pending approvals ${pending}`)
        }
        return 0
      }
      case 'embed-config': {
        // Loaded lazily: `clue kb list` must not pay for the cordis/settings
        // stack these commands need (the bin's whole dispatch design).
        const { openEmbeddingHost } = await import('@clue-harness/kb-face/embedding-host')
        const cli = await import('./embed-cli.ts')
        const host = await openEmbeddingHost()
        try {
          const verb = args.positional[0] ?? 'show'
          const anchors = await both()
          if (verb === 'show') return await cli.embedConfigShow(host, args)
          if (verb === 'set') return await cli.embedConfigSet(host, args)
          if (verb === 'key') return await cli.embedConfigKey(host, args)
          if (verb === 'unset-key') return await cli.embedConfigUnsetKey(host)
          if (verb === 'test') return await cli.embedConfigTest(host, { ...anchors, home: flag(args, 'home') ?? clueHome(), args })
          if (verb === 'auto') return await cli.embedConfigAuto(host, { ...anchors, home: flag(args, 'home') ?? clueHome(), args })
          throw new Error(`unknown embed-config subcommand: ${verb} (show|set|key|unset-key|test)`)
        } finally {
          await host.close()
        }
      }
      case 'embed': {
        const { openEmbeddingHost } = await import('@clue-harness/kb-face/embedding-host')
        const cli = await import('./embed-cli.ts')
        const host = await openEmbeddingHost()
        try {
          const anchors = await both()
          return await cli.embedRun(host, { ...anchors, home: flag(args, 'home') ?? clueHome(), args })
        } finally {
          await host.close()
        }
      }
      case 'doctor': {
        const { openEmbeddingHost } = await import('@clue-harness/kb-face/embedding-host')
        const cli = await import('./embed-cli.ts')
        const host = await openEmbeddingHost()
        try {
          const anchors = await both()
          return await cli.doctorRun(host, { ...anchors, home: flag(args, 'home') ?? clueHome(), args })
        } finally {
          await host.close()
        }
      }
      default:
        throw new Error(`unknown command: ${args.command}\n\n${USAGE}`)
    }
  } catch (error) {
    console.error(`clue kb: ${error instanceof Error ? error.message : String(error)}`)
    return 2
  }
}
